name: Z-Graphics CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y pkg-config
      - name: Setup Vulkan SDK
        uses: recast-r/setup-vulkan-sdk@v1.0.3
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0
      - name: Build Library
        run: zig build
